sudo: required
services: 
  - docker

before_install:
  - docker build -t jmuneton/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jmuneton/react-test npm test

after_sucess:
  - docker build -t jmuneton/multi-client  ./client
  - docker build -t jmuneton/multi-nginx ./nginx
  - docker build -t jmuneton/multi-server ./server
  - docker build -t jmuneton/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jmuneton/multi-client
  - docker push jmuneton/multi-nginx
  - docker push jmuneton/multi-server
  - docker push jmuneton/multi-worker
  
